<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FeedCore.Application\FeedCore.Application.csproj" />
    <ProjectReference Include="..\FeedCore.Core\FeedCore.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meeucg.FitFlow.AIServices" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="11.0.0-preview.3.26207.106" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>
</Project>
