global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: fitflow-http
    metrics_path: /metrics
    static_configs:
      - targets:
          - apigateway:8080
          - raw-postings-filter:8080
          - parsermock:8080

  - job_name: fitflow-grpc
    metrics_path: /metrics
    static_configs:
      - targets:
          - feedcore:8081
          - interview-grpc-api:8081

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets:
          - rabbitmq:15692
