<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>FitFlow.FeedCore.Grpc.Contracts</PackageId>
    <Title>FitFlow FeedCore gRPC Contracts</Title>
    <Authors>https://github.com/meeucg</Authors>
    <Description>Public gRPC contracts for FitFlow FeedCore recommendation service.</Description>
    <Version>1.0.0</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\feedcore.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
